#!/bin/bash

set -e # 命令出错就退出
trap 'catchError $LINENO $BASH_COMMAND' SIGHUP SIGINT SIGQUIT EXIT # 捕获错误情况

catchError() {
    exit_code=$?
    if [ $exit_code -ne 0 ]; then
        fail "\033[31mcommand: $2\n  at $0:$1\n  at $STEP\033[0m"
    fi
    exit $exit_code
}

notice() {
    echo -e "\033[36m $1 \033[0m "
}
success() {
    echo -e "\033[42;37m 成功 \033[0m $1"
}

fail() {
    echo -e "\033[41;37m 失败 \033[0m $1"
}

echo "start $UID"

cd /workspace

if [[ $TEST_MODE == 'false' ]];then
    notice 'normal'
    ./build-appimage.sh
else
    notice 'test'
    ./test/build-appimage.sh
fi

